### ISSUE TITLE
Merging multiple files: missing multi select

### ISSUE THREAD

**Issue by KopiasCsaba** [Swati4star/Images-to-PDF#1049]
Hi!

Today I wanted to use this app to merge 10+pdfs quickly, but I realized that the "add files" option only allows adding files one by one.

Therefore it would be great if selecting multiple files would be enabled. 

Also pdf file names were invisible in the rows for me on a light theme.

And while at it, it would be great to be able to share pdfs with the app and being able to do various things with it! E.g. add to merge, etc.

On v8.8.1, fdroid

Best regards,
Csaba

**Comment by Ramanand-Yadav** [comment]
hey, @KopiasCsaba  let me know. if you are working to fix this issue or assign me this issue I want to work on this.

**Comment by KopiasCsaba** [comment]
Dear @Ramanand-Yadav, please go ahead! Im just a user of the app!

**Comment by codegsaini** [comment]
@KopiasCsaba 
Thanks for your feedback.
1.) Multi-PDF select feature will be added soon.
2.) Regarding PDF name invisible in rows in light theme. It will be fixed soon.
3.) Share PDF feature along with other essential features will be considered to be added soon.

**Comment by codegsaini** [comment]
@Ramanand-Yadav If you want to work on any issue, you can start work on the same as soon as you have the idea about fixing it. There is no need to ask for assignments from anyone ([for information] only the owner of the repository can assign ).
As [doc.github.com states](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#:~:text=Assignees%20clarify%20who%20is%20working%20on%20specific%20issues%20and%20pull%20requests.) -
> Assignees clarify who is working on specific issues and pull requests.

### Anyone can work on any issue with or without an assignment. The assignment only tells the world who is actually working on that issue or pull request so that other people avoid working on the same to not produce conflicts in code.

**Comment by JustinLiang522** [comment]
I am having a course project on fixing issues of open-source android apps, I would like to work on it as well.

**Comment by codegsaini** [comment]
@JustinLiang522 You can work on it.

**Comment by YZ11813227** [comment]
Has this feature been implemented? I'd like to participate in this issue.
