### ISSUE TITLE
Catch files shared via another image viewing app

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#131]
Allow user to do the following : 
- User can view images in `some` application & click on share option
- Our application should appear as an option to `Convert to PDF`
- On clicking this, our `PDF Converter` app should open up on home page with those images selected. ( A message should appear saying that those images are already added & user can just click on `Create PDF` and PDF will be created)

**Comment by ac491** [comment]
I would like to try to solve this issue

**Comment by Swati4star** [comment]
Sure @ac491 👍

**Comment by ac491** [comment]
Hey, I tried implementing it. when the files are shared from other app, we get an arrayList of uris in mainActivity. I pass this arraylist to the homeFragment using a bundle. In homeFragment, I simply add the arrayList to mTempUris. It works for images shared from gallery but does not work for other app like whatsapp. The Uri of the images shared from whatsapp are not showing the real path due to which the app crashes as it cannot locate the image. Can you please suggest something to solve this issue.

**Comment by Swati4star** [comment]
` It works for images shared from gallery but does not work for other app like whatsapp. `
Why is it happening? Do we not have the required permissions?

`The Uri of the images shared from whatsapp are not showing the real path`
I am not able to get this. what uri are we getting for whatsapp images?

**Comment by ac491** [comment]
![img_20180706_112125](https://user-images.githubusercontent.com/31413484/42362069-306a4712-810f-11e8-87da-f284047ab38d.jpg)
This is what i get from uri.getPath for whatsapp images

**Comment by Swati4star** [comment]
@ac491 I think this link might help https://www.dev2qa.com/how-to-get-real-file-path-from-android-uri/

**Comment by Swati4star** [comment]
@ac491 If that doesn't help, you may look into this : https://ebaytech.berlin/receiving-shared-content-on-android-823e9d1286ee

**Comment by ac491** [comment]
Thanks, I will try them out

**Comment by ac491** [comment]
I tried many different methods but nothing seems to work for whatsapp images. I have written a simple method which gets the path from meta data stored in MediaStore, but it still does not work for whatsapp images (but it does work for google photos). I also tried to get the bitmap directly from the inputstream instead of getPath() but it still does not work.

**Comment by Swati4star** [comment]
Then, don't add whatsapp images. Just show the error message, `We could add only x of y images. Please select more images from our **Select Images**` option.
