### ISSUE TITLE
Create a Home Page

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#393]
### Create a new Home frgament

- The UI should look like below. Use horizontal recycler view for this.
- On selecting the items in first & third row, open the respective fragments
- On selecting items in second row, open the `View Files` fragment, and show a dialog.
For example, if user selected `Add Password`, open up `View Files` section & show the dialog saying

```
Follow these steps to add password to the PDF :
- Select the PDF to encrypt
- A dialog will open up, select `Add Password` option.
```
Also, add `Don't show again` checkbox on the dialog.

![img_20180815_123342](https://user-images.githubusercontent.com/9164477/44135802-333f3860-a088-11e8-80c0-823073782b77.jpg)

**Comment by vishalkalra9** [comment]
Hi Swati, I think on home page there should be only options to view and create new as not many users would be coming with the intention to add or remove passwords. Those are mostly required at the time of creating pdfs. Still some might come for removing passwords before sharing so that can be placed at the bottom for better user interface. Also sharing is done after browsing only so View files should be placed first.

**Comment by Swati4star** [comment]
We should move View files & view conversion history to top.
