### ISSUE TITLE
Use Snackbar instead of Toast everywhere in the app

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#65]
All Snackbar related tutorials are there at this link : https://www.androidhive.info/2015/09/android-material-design-snackbar-example/
Remove toast from the code.

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, Can I work on this?

**Comment by Swati4star** [comment]
Hi! yeah sure, you can work on this one. But, I would suggest doing the necessary changes for your previous PR first. 👍

**Comment by subham9777** [comment]
Hello Swati, I want to work on this and am new to open source contribution.

**Comment by anandkumarkparmar** [comment]
Hi @subham9777, I have already started working on this. Can you please pick any other issue?

Welcome to the open source community dude.

**Comment by Swati4star** [comment]
Hi @subham9777, @anandkumarkparmar  is already working on this. You can pick up any other issue, or you can even create a new one.

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, I have two questions related to this change.

1. Some toast had duration as **_LENGTH_SHORT_** and some had **_LENGTH_LONG_**. Is it intentional? Or do you want to make it consistent across app(any one of these durations)?

2. Every message string is starting with **toast_***. Do you want to change the name of every message which we are showing with Snackbar now?

**Comment by Swati4star** [comment]
1. It is not intentional. You can make the duration as per your wish.
2. Yes please, change the strings also to snackbar_*

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, Please review the pull request.

**Comment by Swati4star** [comment]
This issue is fixed. Thanks to @anandkumarkparmar 👍
