### ISSUE TITLE
the gpl code is selling for 18$ on code canyon 

### ISSUE THREAD

**Issue by Ahmadmohiddin** [Swati4star/Images-to-PDF#917]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Ahmadmohiddin** [comment]
LINK:= https://codecanyon.net/item/pdf-creatorconverter-edit-admob/23665682

**Comment by Sinhcoms-LLP** [comment]
> LINK:= https://codecanyon.net/item/pdf-creatorconverter-edit-admob/23665682
Actually this is not guy who is selling it. follow this link 
[https://www.codester.com/items/24157/pdf-converter-android-source-code](https://www.codester.com/items/24157/pdf-converter-android-source-code
) This guys is selling it

**Comment by Swati4star** [comment]
Do you guys know a resource where I can report such things?

**Comment by HenriDellal** [comment]
I'm afraid that even if this guy sells the source code, it doesn't make him the license violator since GPL doesn't limit ability to sell software. If he actually did violated it by other means (e.g. has no license mentions in the application), then you may contact Free Software Foundation (read more at https://www.gnu.org/licenses/gpl-violation.html). I'd also get in touch with Envato/CodeCanyon first since they host this advertisement.

**Comment by czlucius** [comment]
If the seller did not distribute it together with the original source code, it is a violation of the GPL.
